### ISSUE TITLE
[Crash] Incompatibility with Roadrunner Entity Tracking mixins when an ender pearl zombie decides to mount a boat

### ISSUE THREAD

**Issue by NighthowlerStudios** [Insane96/EnhancedAI#75]
**Describe the bug**
This crash occured whilst a player was being chased by an ender pearl zombie and both entered a boat. 

It is due to the tracking behaviours having become event based in roadrunner, which cannot happen twice per tick, so make sure the ai only has one tracking task at a time by using a comparison check to avoid adding another task if one already exists.

Theoretically it is unsafe to add two simultaneous tasks to a goal based AI anyway, so this should truly be patched by this mod and not roadrunner

This crash can be prevented by disabling roadrunner's mixin.ai.nearbyentitytracking mixin in their rules config

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.39
 - Enhanced AI: 1.2.3
 - InsaneLib: 1.4.2

**Steps to reproduce**
1. Trigger a chase from a zombie holding an ender pearl
2. Summon a boat and enter it
3. Position the boat in a way that allows the enderpearl zombie to enter it

**Logs**
https://pastebin.com/XG03kSk6

**Can the issue be reproduced with a mininal set of mods? (E.g. EnhancedAI + InsaneLib + Tinkers' Construct)**
Yes (Enhanced AI, InsaneLib, Roadrunner)

**Comment by Insane96** [comment]
1.16.5 is no longer supported. Also I don't understand what's the problem

**Comment by Kaleidio** [comment]
java.lang.IllegalStateException: Adding Entity listener a second time: me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityListenerMulti@7eb1791c with sublisteners: [me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityTracker@6befe50c for entity class: 

this fails because it's trying to force the zombie's mount to move as your mod provides mixins that allow mounted entities to control the direction their mount moves.  roadrunner does not allow you to process two player search actions at once for the same tracker entity.

**Comment by NighthowlerStudios** [comment]
whoops sorry, I meant to post this to SpecialAI

**Comment by NighthowlerStudios** [comment]
From what I understand I mistook the names of your two mods by accident, I apologize.
