### ISSUE TITLE
Mob Ideas

### ISSUE THREAD

**Issue by RedRegion** [Insane96/EnhancedAI#87]
I made a mod similar to this many years ago on bedrock and could not figure out how to port it over to java so I figured you can use some of this if you wanted, some of this stuff may be a repeater of things already in the mod though

All Hostile Mobs
increased damage
increased health
movement speed matched the players walking speed
view distance of 100 blocks and through walls
Will not attack skeletons or pillagers if accidentally shot
In addition to targeting players they also attacked Villagers, Animals, and Iron golems (before being hit first)

All Animals
Would run away when the player and hostile mobs got to close

Item Changes
Ender pearls would have a 50% chance of spawning an endermite 
Snow balls would give a player blindness for 1 second when hit (I don't think players can hit themselves with snowballs 
in java so this might be useless)
Tnt would always cause a fire (same for minecraft tnt)
Xp bottles give a substantial more ammount of xp

Blaze
would shoot every .1 seconds for 2 seconds then recharge for 7 seconds

Cave Spider
In addition to poisoning a player on hit they would also cause nausea 

Creeper
Yours already does what mine did and more, but just not all at once and at random intervals 

Drowned
Would outswim players by double the speed and throw their tridents much faster

Elder Guardian
Would summon 2 Guardians to help it when it got below half health

Ender Dragon
Moved much faster
Fires its projectile much faster

Enderman
Would blind players when it hit them

Endermite
Would teleport like an enderman would

Evoker
Would summon two vexes instead of the normal one at a time
Can open doors

Ghast
Would shoot faster
Fireballs had a bigger explosion radius

Guardian
had a bigger attack range

Husk
hunger debuff increased to one minute

Iron golem
Increased damage to compete with increased mob health
Health increased to 150 to compete with harder hitting mobs

Magma Cube
Would move quickly through lava to reach the player

Phantom
Nothing changed (already annoying enough)

Pillager
Would shoot from a longer range
Would shoot slowness arrows
Can open doors

Ravager
Would break through common building blocks (block list is over 100 lines long so I won't paste it)
Would let any hostile mob ride on it's back

Shulker
The levitation effect was buffed to levitation V with the same duration

Silverfish
The radius turning silverfish blocks back into regular blocks when hitting another silverfish was increased

Skeleton
Can fire from a farther distance
Would fire weakness arrows

Slime
Could jump a little higher than normal

Spider
All hostile mobs were able to ride on it's back
When it hit a player it would apply nausea 

Stray
Could fire farther

Vex
Nothing changed aside from the buffs all mobs got

Vindicator
Will instantly break down doors

Villager
Will run from all hostile mobs since all of the mobs target them now
Would turn into a zombie villager when killed by any hostile mob or player

Witch
Would randomly summon 3 zombies when fighting with a cap of 6 summoned at once

Wither
Would move faster and fire more frequently

Wither Skeleton
Nothing changed aside from the buffs all mobs got

Wolf
Buffed hp and damage to compete with mob buffs

Zombie
Will break down doors without randomly stopping, even if the player is not in sight

Other things I never got around to adding/testing
Skeletons drawing out swords when getting approached by a player and then pulling their bow back out if the player started to run
Making armor and weapons more common among zombies 
Witches would randomly buff other mobs
A zombie would sometimes drop a silverfish when killed
Spiders would sometimes spawn with a cave spider riding on their back
Give some mobs specials or a boost when they went below half health
Make ranged mobs smarter by trying to avoid shooting people in front of them
Exploding arrows for skeletons >.>
Pillagers could sometimes shoot firework rockets instead of arrows from their crossbows

**Comment by Insane96** [comment]
Long comment ahead
> increased damage
> increased health
> movement speed matched the players walking speed

No, Mobs Properties Randomness can do that and more.

> view distance of 100 blocks and through walls

Can already be done

> Will not attack skeletons or pillagers if accidentally shot

Already a thing, mobs don't attack eachother

- [ ] In addition to targeting players they also attacked Villagers, Animals, and Iron golems (before being hit first)
- [x] Would run away when the player and hostile mobs got to close

That's something that I can add

> Ender pearls would have a 50% chance of spawning an endermite

Endermites are just annoying.

> Snow balls would give a player blindness for 1 second when hit (I don't think players can hit themselves with snowballs
in java so this might be useless)

Nope, you can't, until the new Combat

> Tnt would always cause a fire

Doesn't make sense and not really fit in the mod

> Xp bottles give a substantial more ammount of xp

Already a thing in Survival Reimagined (former IguanaTweaks Reborn)

> would shoot every .1 seconds for 2 seconds then recharge for 7 seconds

Can already be configured

> In addition to poisoning a player on hit they would also cause nausea

Nausea is bad

> Would outswim players by double the speed and throw their tridents much faster

They already swim faster, not a fan of trowing tridents faster

> Elder Guardian, Ender Dragon and Wither

Progressive Bosses does what you suggested and more

> Enderman

Stuff's already planned for them

> Endermites

Useless mob, so useless that even buffing it wouldn't change a thing

> Would summon two vexes instead of the normal one at a time

They already summon 2/3 iirc, and they are already annoying to deal with

- [ ] Evokers can open doors

> Ghast

Already buffed and explosion radius can be changed with MPR

- [ ] Guardians have a bigger attack range
Not a huge fan of the idea, but I need to test it

> hunger debuff increased to one minute

Can be done with MPR

Part 2 coming soon lol

**Comment by RedRegion** [comment]
lol ty for the feedback, I knew most of it was bad but I just threw it all out there to see what you did and didn't like and to hopefully have a few things you could use

**Comment by Insane96** [comment]
> Iron golem
Increased damage to compete with increased mob health
Health increased to 150 to compete with harder hitting mobs

- [x] Can be done with MPR, but will probably add something to EnhancedAI to compensate for the other mobs buffs

> Magma Cube
Would move quickly through lava to reach the player

- [ ] I'll check if it's doable

> Pillager
Would shoot from a longer range
Would shoot slowness arrows
Can open doors

- [ ] Definitely need a slight better AI like skellys
- [ ] Not a fan of slowness arrows
- [ ] Strange they can't already open doors, will add that

> Ravager
Would break through common building blocks (block list is over 100 lines long so I won't paste it)
Would let any hostile mob ride on it's back

- This sounds too much like griefing, don't really like the idea.
- Sure, but the ravager only spawns in raids.

> Shulker
The levitation effect was buffed to levitation V with the same duration

- [ ] Yeah something like this can be done

> Silverfish
The radius turning silverfish blocks back into regular blocks when hitting another silverfish was increased

- [ ] Sure, I'll check what I can do

> Skeleton
Can fire from a farther distance
Would fire weakness arrows

The first can already be done, don't like the second idea (And can also be done with MPR)

> Slime
Could jump a little higher than normal

- [ ] Need to explore the idea

> Spider
All hostile mobs were able to ride on it's back
When it hit a player it would apply nausea

- [ ] Sure, mobs should be able to go ride them
- Nah, nausea is annoying and not motion sickness friendly

> Stray
Could fire farther

They already do

Vex
Nothing changed aside from the buffs all mobs got

I would nerf them, stupidly small, hard to hit and deal too much damage

> Vindicator
Will instantly break down doors

- [ ] Instantly no, but yeah, the axe they have might be useful 

> Villager
Will run from all hostile mobs since all of the mobs target them now
Would turn into a zombie villager when killed by any hostile mob or player

- [ ] Will probably add something like that
- Makes no sense

> Witch
Would randomly summon 3 zombies when fighting with a cap of 6 summoned at once

They are already buffed enough

> Wither
Would move faster and fire more frequently

Just use Progressive Bosses lol

> Wither Skeleton
Nothing changed aside from the buffs all mobs got

Some changes are planned for them

> Wolf
Buffed hp and damage to compete with mob buffs

- [ ] Will probably do something like Iron Golems

> Zombie
Will break down doors without randomly stopping, even if the player is not in sight

- This is just griefing

> Skeletons drawing out swords when getting approached by a player and then pulling their bow back out if the player started to run

I don't like the idea of making Skeletons go melee
> Making armor and weapons more common among zombies

Use MPR
> Witches would randomly buff other mobs

This is already planned but not really easy to do
> A zombie would sometimes drop a silverfish when killed

- What
> Spiders would sometimes spawn with a cave spider riding on their back

- [ ] This is mean, i like 
> Give some mobs specials or a boost when they went below half health

Nah, mobs are good already as they are
> Make ranged mobs smarter by trying to avoid shooting people in front of them

Already done
> Exploding arrows for skeletons >.>

Just install Archers Paradox and use MPR lol
>Pillagers could sometimes shoot firework rockets instead of arrows from their crossbows

- [ ] Yeah, I think they should have more firework rockets

**Comment by Insane96** [comment]
Moved this to #96
