### ISSUE TITLE
[1.18.2]  Rotten Creature's Undead Miner cannot be set as a Digger

### ISSUE THREAD

**Issue by Reshy** [Insane96/EnhancedAI#93]
**Describe the bug**  
Although the Undead Miner from Rotten Creatures cannot be setup to be a digger, despite using zombie mechanics and AI.

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.18.2
 - Forge:  40.2.1
 - Enhanced AI: EnhancedAI-1.6.5-mc1.18.2.jar
 - InsaneLib: InsaneLib-1.5.3-mc1.18.2.jar

**Steps to reproduce**  
1.   Set whitelist to true for digger zombies
2.   apply whitelist to "rottencreatures:undead_miner"
3.   Crash

**Logs**  
https://pastebin.com/PkPyy61n

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
No

**Comment by Insane96** [comment]
You don't need to set the whitelist for mobs if they already inherit from zombies.
Also the game crashed because your config is invalid.

**Comment by BigJMoney** [comment]
@Insane96
>You don't need to set the whitelist for mobs if they already inherit from zombies.

What does inherit mean in this context? I used KubeJS to get a list of all entity_type and their tags, and `rottencreatures:undead_miner` does not have the `enhancedai:can_be_miner` tag. Is there some code that allows creatures to inherit behavior without needing tags? Is there a way for me to find out what creatures are successfully inheriting from others? I ask because none of the mobs in the mods I'm using are picking up enhanced AI tags, and I've been assuming that's something I must set manually in a datapack or with KubeJS.

**Comment by Insane96** [comment]
In 1.20 it's different. You need to use entity type tags to allow modded mobs to use certain features. Refer to the wiki
